blogProject/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
	url(r'zhougb3', views.about, name = 'about')
]

blogProject/blogProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('usermanager.urls')),
    url(r'', include('comments.urls')),    
]

blogProject/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

blogProject/usermanager/urls.py
from django.conf.urls import url
from . import views

app_name = 'usermanager'

urlpatterns = [
	url(r'^register/$', views.register, name = 'register'),
	url(r'login/$', views.login, name = 'login'),
	url(r'^register/api/$', views.registerapi, name = 'registerapi'),
	url(r'login/api/$', views.loginapi, name = 'loginapi'),
]

blogProject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse

# Create your models here.
# 
@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(max_length = 100)
	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Tag(models.Model):
	name = models.CharField(max_length = 100)
	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Post(models.Model):
	title = models.CharField(max_length = 70)
	body = models.TextField()

	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()

	excerpt = models.CharField(max_length = 200, blank = True)

	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank = True)

	author = models.ForeignKey(User)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk': self.pk})

blogProject/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible
from django.contrib.auth.models import User
from blog.models import Post
# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
	created_time = models.DateTimeField(auto_now_add=True)
	text = models.TextField()
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)

	def __str__(self):
		return self.text[:20]

blogProject/usermanager/models.py
from django.db import models

# Create your models here.

blogProject/usermanager/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class RegisterForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

	class Meta:
		model = User
        #表单对应的字段名，是这个类里面有的。
		fields = ['username', 'email']

	def clean_password2(self):
 		cd = self.cleaned_data
 		if cd['password'] != cd['password2'] :
 			raise forms.ValidationError(u"校验密码错误")
 		return cd['password2']

	def clean_username(self):
 		username = self.cleaned_data['username']
 		users = User.objects.filter(username = username).count()
 		if users:
 			raise forms.ValidationError(u'用户名已经存在！')
 		return username

	def clean_email(self):
 		email = self.cleaned_data['email']
 		email_count = User.objects.filter(email = email).count()
 		if email_count:
 			raise forms.ValidationError(u'邮箱已经存在！')
 		return email

class LoginForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username']

	def clean_username(self):
		username = self.cleaned_data['username']
		users = User.objects.filter(username = username).count()
		if not users:
			raise forms.ValidationError(u'用户名不存在！')
		return username

	def clean_password(self):
		cd = self.cleaned_data
		users = User.objects.filter(username = cd.get('username')).count()
		if users:
			user = authenticate(username=cd['username'], password=cd[password])
			if not user:
				raise forms.ValidationError(u'密码不正确！')
		return cd['password']

blogProject/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post, Category
from comments.form import CommentForm
from comments.models import Comment
import markdown
# Create your views here.

def index(request):
	post_list = Post.objects.all().order_by('-created_time')
	return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.body = markdown.markdown(post.body,extensions=['markdown.extensions.extra','markdown.extensions.codehilite','markdown.extensions.toc',])
	comment_list = post.comment_set.all()
	return render(request, 'blog/detail.html', context={'post': post, 'form':CommentForm(), 'comment_list':comment_list})

def archives(request, year, month):
	post_list = Post.objects.filter(created_time__year=year,created_time__month=month).order_by('-created_time')
	return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk):
	cate = get_object_or_404(Category, pk=pk)
	post_list = Post.objects.filter(category=cate).order_by('-created_time')
	return render(request, 'blog/index.html', context={'post_list': post_list})

def about(request):
	return render(request, 'about.html')

blogProject/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from blog.models import Post
from .models import Comment
from .form import CommentForm
# Create your views here.

def post_comment(request, post_pk):
	post = get_object_or_404(Post, pk=post_pk)
	if request.method == 'POST':
		if request.session.get('username', False):
			form = CommentForm(request.POST)
			if form.is_valid():
				comment = form.save(commit=False)
				comment.post = post
				comment.user = User.objects.filter(username= request.session['username'])[0]
				comment.save()
				return redirect(post)
	return redirect('/login')

blogProject/usermanager/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

# Create your views here.
def register(request):
	return render(request, 'usermanager/register.html',context={'form':RegisterForm()})

def login(request):
	if (request.session.get('username', False)):
		return redirect('/')
	return render(request, 'usermanager/login.html', context={'form':LoginForm()})

def registerapi(request):
	if(request.method == 'POST'):
		username = request.POST.get('username', '')
		password = request.POST.get('password', '')
		password2 = request.POST.get('password2', '')
		email = request.POST.get('email', '')
		obj = RegisterForm(request.POST)
		if obj.is_valid:
			if password != password2 or User.objects.filter(username = username).count() != 0 or User.objects.filter(email = email).count() != 0 :
				return render(request, 'usermanager/register.html', context={'form':obj})
		user = User()
		user.username = username
		user.email = email
		user.set_password(password)
		user.save()
		if (not request.session.get('username', False)):		
			newUser=authenticate(username=username,password=password)
			if newUser is not None:  
				request.session['username'] = username  
				request.session.set_expiry(60)  
		return redirect('/')	
	return render(request, 'usermanager/register.html', context={'form': RegisterForm()})

def loginapi(request):
	if request.method == 'POST':
		username = request.POST.get('username', '')
		password = request.POST.get('password', '')
		obj = LoginForm(request.POST)
		user = authenticate(username=username,password=password)
		if user:
			request.session['username'] = username  
			request.session.set_expiry(60)  
			return redirect('/')
		return render(request, 'usermanager/login.html', context={'form':obj})		
	return render(request, 'usermanager/login.html', context={'form':LoginForm()})

blogProject/templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>about</title>
</head>
<body>
	<div>
		<h1><a href="https://github.com/zhougb3">我的github地址</a></h1>
		<h1><a href="http://my.csdn.net/zhougb3">我的CSDN博客地址</a></h1>		
	</div>
</body>
</html>

blogProject/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    {% if request.session.username %}
                    <h1><a href="{% url 'blog:index' %}"><b>Zero</b> &amp; One  {{request.session.username}}</a></h1>
                    {% else %}
                    <h1><a href="{% url 'blog:index' %}"><b>Zero</b> &amp; One </a></h1>
                    {% endif %}
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'usermanager:login' %}" data-hover="登录">登录</a></li>
                            <li class="cl-effect-11"><a href="{% url 'usermanager:register' %}" data-hover="注册">注册</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        <li>暂时无文章！</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                        <ul>
                            {% for date in date_list %}
                                <li>
                                  <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                                </li>
                            {% empty %}
                            <li>暂时无归档！</li>
                            {% endfor %}
                        </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">(13)</span></a>
                            </li>
                        {% empty %}
                        <li>暂时无分类！</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&Copyright 2017 by zhougb3</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

blogProject/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blogProject/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blogProject/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{post.title}}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{post.created_time}}</time></a></span>
                <span class="post-author"><a href="#">{{post.author}}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">588 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{post.body | safe}}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                  <label for="{{ form.text.id_for_label }}">评论：</label>
                  {{ form.text }}
                  {{ form.text.errors }}
                  <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.user.username}}</span>
                    <time class="submit-date">{{ comment.created_time }}</time>
                    <div class="text">
                    {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

            

blogProject/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{% url 'blog:detail' post.pk %}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">{{post.created_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author}}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="#">588 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{post.excerpt}}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class = "no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
 {% endblock main %}

blogProject/templates/usermanager/login.html
{% extends 'base.html' %}
{% block main %}
<form action="{% url 'usermanager:loginapi' %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.username.id_for_label }}">名字：</label>
      {{ form.username }}
      {{ form.username.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.password.id_for_label }}">密码：</label>
      {{ form.password }}
      {{ form.password.errors }}
      <button type="submit" class="comment-btn">登录</button>
    </div>
  </div>    <!-- row -->
</form>
 {% endblock main %}

blogProject/templates/usermanager/register.html
{% extends 'base.html' %}
{% block main %}
<form action="{% url 'usermanager:registerapi' %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.username.id_for_label }}">名字：</label>
      {{ form.username }}
      {{ form.username.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">邮箱：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.password.id_for_label }}">密码：</label>
      {{ form.password }}
      {{ form.password.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.password2.id_for_label }}">确认密码：</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type="submit" class="comment-btn">注册</button>
    </div>
  </div>    <!-- row -->
</form>
 {% endblock main %}